### PR TITLE
Package rename

### PR DESCRIPTION
**Pull request by mainstringargs**
@manoelcampos does this look right or did I misunderstand?

### CODE REVIEW

**Comment by manoelcampos** [comment]
I don't think just changing the `build.gradle` will do. The `groupId` is supposed to be an actual package, for consistency. This way, you should have an `alphavantagescraper` inside [mainstringargs](https://github.com/mainstringargs/alpha-vantage-scraper/tree/package-rename/src/main/java/io/github/mainstringargs) directory, moving everything there.
But since there was an `alphaVantageScraper` dir already, you should consider changing its name.
The directory structure should be something like:

* mainstringargs/alphavantagescraper
  * input
  * output
  * alphaVantageScraper (which should be renamed)

**Comment by mainstringargs** [comment]
Ah. That makes sense.  I’ll take a look.

**Review by manoelcampos — CHANGES_REQUESTED** [review]
I think that is it. You just have to bump version number in build.gradle. It's still `1.4`

**Review by manoelcampos — APPROVED** [review]
That is it. Thanks for the great lib.

**Pull request merged**
