### PR TITLE
Fix version number and project name

### PR DESCRIPTION
**Pull request by manoelcampos**
# Versions fixed on build.gradle and pom.xml

- Since there is a 1.3 tag already, version was updated to 1.4.0 (following semantic versioning)
- Fix some references from the previous project
  - Fix group id on build.grade.
  - Fix project name references on pom.xml
  - Adds developer name on pom.xml

Could you please release the 1.4.0 version to Maven Central and let me know? 
I have another project depending on it.

### CODE REVIEW

**Comment by manoelcampos** [comment]
By the way, since you have created an independent project, [you can send GitHub an email requesting to unlink your fork from the original project](https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository). I've done this for one of my projects.

**Comment by mainstringargs** [comment]
Thanks for these updates.  I didn't know you could unlink a fork.  That's a good tip.  I will release the 1.4.0 version tomorrow.  I am away from my computer today.  Cheers!

**Comment by mainstringargs** [comment]
Ok, so I've put in a ticket to unlink the fork, and I've pushed 1.4.0.  It's not showing on the maven central web page yet, but the badge updated to 1.4.0, so I think that's a good sign.

**Comment by manoelcampos** [comment]
The new version is showing for me on Maven Central now. Thanks.

**Pull request merged**
